#!/usr/bin/env bash
set -euo pipefail

############################
# Environment configuration
############################

PROJECT_ROOT="/home/toorajtaraz/Documents/projects/lab/mem_alloc_exprs"
ALLOC_LIB_DIR="$PROJECT_ROOT/installed_for_mem_alloc_exprs/lib64"

export LD_LIBRARY_PATH="$PROJECT_ROOT/installed_for_mem_alloc_exprs/lib:${LD_LIBRARY_PATH:-}"
export PATH="$PROJECT_ROOT/installed_for_mem_alloc_exprs/bin:${PATH}"

PYTHON_SCRIPT="src/count_mem_calls.py"


########################################
# Allocators to test
########################################
# key = label, value = allocator .so
# empty value → GNU / system malloc

declare -A ALLOCATORS=(
  # [gnu]="gnu"
  [mimalloc]="libmimalloc.so"
  # [jemalloc]="libjemalloc.so"
  # [hoard]="libhoard.so"
)

########################################
# Commands to test
########################################

COMMANDS=(
  "foamTestTutorial -parallel -full /home/toorajtaraz/Documents/projects/lab/mem_alloc_exprs/openfoam/openfoam/tutorials"
  "foamTestTutorial -parallel -full basic/chtMultiRegionFoam/2DImplicitCyclic"
  "foamTestTutorial -parallel -full basic/laplacianFoam/flange"
  "foamTestTutorial -parallel -full basic/laplacianFoam/implicitAMI-nonblocking"
  "foamTestTutorial -parallel -full basic/laplacianFoam/multiWorld1"
  "foamTestTutorial -parallel -full basic/laplacianFoam/multiWorld2"
  "foamTestTutorial -parallel -full basic/overLaplacianDyMFoam/heatTransfer"
  "foamTestTutorial -parallel -full basic/overLaplacianDyMFoam/heatTransferFluxConservation1D"
  "foamTestTutorial -parallel -full basic/overPotentialFoam/cylinder"
  "foamTestTutorial -parallel -full basic/overPotentialFoam/cylinder/cylinderAndBackground"
  "foamTestTutorial -parallel -full basic/potentialFoam/cylinder"
  "foamTestTutorial -parallel -full basic/potentialFoam/pitzDaily"
  "foamTestTutorial -parallel -full basic/scalarTransportFoam/pitzDaily"
  "foamTestTutorial -parallel -full combustion/chemFoam/gri"
  "foamTestTutorial -parallel -full combustion/chemFoam/gri/validation"
  "foamTestTutorial -parallel -full combustion/chemFoam/h2"
  "foamTestTutorial -parallel -full combustion/chemFoam/h2/validation"
  "foamTestTutorial -parallel -full combustion/chemFoam/ic8h18"
  "foamTestTutorial -parallel -full combustion/chemFoam/ic8h18_TDAC"
  "foamTestTutorial -parallel -full combustion/chemFoam/ic8h18_TDAC/validation"
  "foamTestTutorial -parallel -full combustion/chemFoam/ic8h18/validation"
  "foamTestTutorial -parallel -full combustion/chemFoam/nc7h16"
  "foamTestTutorial -parallel -full combustion/chemFoam/nc7h16/validation"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/compartmentFire"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/flameSpreadWaterSuppressionPanel"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/oppositeBurningPanels"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/simplePMMApanel"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/smallPoolFire2D"
  "foamTestTutorial -parallel -full combustion/fireFoam/LES/smallPoolFire3D"
  "foamTestTutorial -parallel -full combustion/PDRFoam/flamePropagationWithObstacles"
  "foamTestTutorial -parallel -full combustion/PDRFoam/pipeLattice"
  "foamTestTutorial -parallel -full combustion/reactingFoam/RAS/chokedNozzle"
  "foamTestTutorial -parallel -full combustion/reactingFoam/RAS/DLR_A_LTS"
  "foamTestTutorial -parallel -full combustion/reactingFoam/RAS/membrane"
  "foamTestTutorial -parallel -full combustion/reactingFoam/RAS/SandiaD_LTS"
  "foamTestTutorial -parallel -full combustion/rhoReactingFoam/groundAbsorption"
  "foamTestTutorial -parallel -full combustion/XiDyMFoam/annularCombustorTurbine"
  "foamTestTutorial -parallel -full combustion/XiDyMFoam/oscillatingCylinder"
  "foamTestTutorial -parallel -full combustion/XiEngineFoam/kivaTest"
  "foamTestTutorial -parallel -full combustion/XiFoam/RAS"
  "foamTestTutorial -parallel -full compressible/acousticFoam/obliqueAirJet"
  "foamTestTutorial -parallel -full compressible/overRhoPimpleDyMFoam/twoSimpleRotors"
  "foamTestTutorial -parallel -full compressible/overRhoSimpleFoam/hotCylinder"
  "foamTestTutorial -parallel -full compressible/overRhoSimpleFoam/hotCylinder/cylinderAndBackground"
  "foamTestTutorial -parallel -full compressible/rhoCentralFoam/biconic25-55Run35"
  "foamTestTutorial -parallel -full compressible/rhoCentralFoam/LadenburgJet60psi"
  "foamTestTutorial -parallel -full compressible/rhoCentralFoam/shockTube"
  "foamTestTutorial -parallel -full compressible/rhoPimpleAdiabaticFoam/rutlandVortex2D"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/laminar/helmholtzResonance"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/laminar/sineWaveDamping"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/aerofoilNACA0012"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/angledDuct"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/angledDuctLTS"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/annularThermalMixer"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/externalCoupledSquareBendLiq"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/mixerVessel2D"
  "foamTestTutorial -parallel -full compressible/rhoPimpleFoam/RAS/squareBendLiq"
  "foamTestTutorial -parallel -full compressible/rhoPorousSimpleFoam/angledDuct/explicit"
  "foamTestTutorial -parallel -full compressible/rhoPorousSimpleFoam/angledDuct/implicit"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/aerofoilNACA0012"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/angledDuctExplicitFixedCoeff"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/gasMixing/injectorPipe"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/squareBend"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/squareBendLiq"
  "foamTestTutorial -parallel -full compressible/rhoSimpleFoam/squareBendLiqNoNewtonian"
  "foamTestTutorial -parallel -full compressible/sonicFoam/laminar/shockTube"
  "foamTestTutorial -parallel -full compressible/sonicFoam/RAS/nacaAirfoil"
  "foamTestTutorial -parallel -full compressible/sonicLiquidFoam"
  "foamTestTutorial -parallel -full discreteMethods/dsmcFoam/freeSpacePeriodic"
  "foamTestTutorial -parallel -full discreteMethods/dsmcFoam/freeSpaceStream"
  "foamTestTutorial -parallel -full discreteMethods/dsmcFoam/supersonicCorner"
  "foamTestTutorial -parallel -full discreteMethods/dsmcFoam/wedge15Ma5"
  "foamTestTutorial -parallel -full discreteMethods/molecularDynamics/mdEquilibrationFoam/periodicCubeArgon"
  "foamTestTutorial -parallel -full discreteMethods/molecularDynamics/mdEquilibrationFoam/periodicCubeWater"
  "foamTestTutorial -parallel -full discreteMethods/molecularDynamics/mdFoam/nanoNozzle"
  "foamTestTutorial -parallel -full DNS/dnsFoam/boxTurb16"
  "foamTestTutorial -parallel -full electromagnetics/mhdFoam/hartmann"
  "foamTestTutorial -parallel -full finiteArea/liquidFilmFoam/cylinder"
  "foamTestTutorial -parallel -full finiteArea/sphereSurfactantFoam/sphereTransport"
  "foamTestTutorial -parallel -full finiteArea/surfactantFoam/planeTransport"
  "foamTestTutorial -parallel -full heatTransfer/buoyantBoussinesqPimpleFoam/hotRoom"
  "foamTestTutorial -parallel -full heatTransfer/buoyantBoussinesqSimpleFoam/hotRoom"
  "foamTestTutorial -parallel -full heatTransfer/buoyantBoussinesqSimpleFoam/iglooWithFridges"
  "foamTestTutorial -parallel -full heatTransfer/buoyantPimpleFoam/hotRoom"
  "foamTestTutorial -parallel -full heatTransfer/buoyantPimpleFoam/hotRoomWithThermalShell"
  "foamTestTutorial -parallel -full heatTransfer/buoyantPimpleFoam/hotRoomWithThermalShell.multi-area"
  "foamTestTutorial -parallel -full heatTransfer/buoyantPimpleFoam/thermocoupleTestCase"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/buoyantCavity"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/circuitBoardCooling"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/comfortHotRoom"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/hotRadiationRoom"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/hotRadiationRoomFvDOM"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/roomWithThickCeiling"
  "foamTestTutorial -parallel -full heatTransfer/buoyantSimpleFoam/simpleCarSolarPanel"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/externalCoupledHeater"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/externalSolarLoad"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/multiRegionHeater"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/reverseBurner"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/snappyMultiRegionHeaterImplicit"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/solarBeamWithTrees"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/windshieldCondensation"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionFoam/windshieldDefrost"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionSimpleFoam/cpuCabinet"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionSimpleFoam/externalCoupledHeater"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionSimpleFoam/heatExchanger"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionSimpleFoam/jouleHeatingSolid"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionSimpleFoam/multiRegionHeaterRadiation"
  "foamTestTutorial -parallel -full heatTransfer/chtMultiRegionTwoPhaseEulerFoam/solidQuenching2D"
  "foamTestTutorial -parallel -full heatTransfer/overBuoyantPimpleDyMFoam/movingBox"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/motorBike"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/naca0012/laminar/drag"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/naca0012/laminar/lift"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/naca0012/laminar/moment"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/naca0012/turbulent/liftFullSetup"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/naca0012/turbulent/liftMinimumSetup"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/sbend/laminar"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/sbend/turbulent/highRe"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/sbend/turbulent/lowRe/multiPoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/sensitivityMaps/sbend/turbulent/lowRe/singlePoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/fork-uneven/flowRate"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/fork-uneven/flowRatePartition"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/fork-uneven/uniformityPatch"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/motorBike"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/naca0012/kOmegaSST/lift"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/naca0012/laminar/drag/primalAdjoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/naca0012/laminar/lift/opt/constraintProjection"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/naca0012/laminar/moment/primalAdjoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/naca0012/laminar/multipleConstraints"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/opt/constrained/SQP"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/opt/unconstrained/losses/BFGS"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/opt/unconstrained/losses/BFGS-transformBox"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/opt/unconstrained/losses/SD"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/opt/unconstrained/uniformityCellZone"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/laminar/primalAdjoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/kOmegaSST/opt"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/losses/BFGS-continuation"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/losses/BFGS/multiPoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/losses/BFGS-oneGo"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/losses/BFGS/op1"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/losses/BFGS/op2"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/nutSqr"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/opt/powerDissipation"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/primalAdjoint"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/shapeOptimisation/sbend/turbulent/SA/primalAdjointFullSetup"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet_Dual_Bottleneck/losses-mass-30-70"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet_Dual_Bottleneck/losses-mass-50-50"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet_Dual_Bottleneck/losses-mass-70-30"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/levelSet/R_05x_NB_01x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/levelSet/R_05x_NB_02x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/levelSet/R_10x_NB_01x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/levelSet/R_10x_NB_02x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/porosityBased/R_05x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/porosityBased/R_10x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/porosityBased/R_10x-init"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/porosityBased/R_20x"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/1_Inlet_2_Outlet/porosityBased/R_20x_massConstr"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/3DBox/losses"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/3DBox/losses-mass"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/3DBox/losses-mass-uniformity"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/3DBox/losses-mass-uniformity-SQP"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/laminar/3DBox/losses-mass-uniformity-SQP-extraVars"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/levelSet/R_05x_NB_01"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/levelSet/R_10x_NB_01"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/levelSet/R_10x_NB_02"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/levelSet/R_20x_NB_01"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/BP/losses"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/BP/losses-massConstr"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/BP/uniformity-losses"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/linear/losses"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/linear/losses-massConstr"
  "foamTestTutorial -parallel -full incompressible/adjointOptimisationFoam/topologyOptimisation/monoFluidAero/turbulent/1_Inlet_2_Outlet/porosityBased/linear/uniformity-losses"
  "foamTestTutorial -parallel -full incompressible/boundaryFoam/steadyBoundaryLayer"
  "foamTestTutorial -parallel -full incompressible/boundaryFoam/steadyBoundaryLayer/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/icoFoam/cavity"
  "foamTestTutorial -parallel -full incompressible/icoFoam/cavityMappingTest"
  "foamTestTutorial -parallel -full incompressible/icoFoam/elbow"
  "foamTestTutorial -parallel -full incompressible/lumpedPointMotion/bridge"
  "foamTestTutorial -parallel -full incompressible/lumpedPointMotion/bridge/steady"
  "foamTestTutorial -parallel -full incompressible/lumpedPointMotion/building"
  "foamTestTutorial -parallel -full incompressible/lumpedPointMotion/building/steady"
  "foamTestTutorial -parallel -full incompressible/overPimpleDyMFoam/cylinder"
  "foamTestTutorial -parallel -full incompressible/overPimpleDyMFoam/cylinder/cylinderAndBackground"
  "foamTestTutorial -parallel -full incompressible/overPimpleDyMFoam/rotatingSquare"
  "foamTestTutorial -parallel -full incompressible/overPimpleDyMFoam/simpleRotor"
  "foamTestTutorial -parallel -full incompressible/overPimpleDyMFoam/twoSimpleRotors"
  "foamTestTutorial -parallel -full incompressible/overSimpleFoam/aeroFoil"
  "foamTestTutorial -parallel -full incompressible/overSimpleFoam/aeroFoil/background_overset"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/contactAngleCavity"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/contaminatedDroplet2D"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/cylinder2D"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/inclinedPlaneFilm"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/mixerVesselAMI2D/mixerVesselAMI2D"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/mixerVesselAMI2D/mixerVesselAMI2D-topologyChange"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/planarPoiseuille"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/planarPoiseuille/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/laminar/sloshing2D"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/decayIsoTurb"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/NACA4412"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/periodicHill"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/periodicHill/steadyState"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/periodicHill/transient"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/periodicPlaneChannel"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/planeChannel"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/planeChannel/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/surfaceMountedCube"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/surfaceMountedCube/fullCase"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/surfaceMountedCube/initChannel"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/vortexShed"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/wallMountedHump"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/LES/wallMountedHump/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/axialTurbine_rotating_oneBlade"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/ellipsekkLOmega"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/oscillatingInletACMI2D"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/propeller1"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/propeller"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/rotatingFanInRoom"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/TJunctionFan"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/TJunctionSwitching"
  "foamTestTutorial -parallel -full incompressible/pimpleFoam/RAS/wingMotion"
  "foamTestTutorial -parallel -full incompressible/pisoFoam/laminar/porousBlockage"
  "foamTestTutorial -parallel -full incompressible/pisoFoam/LES/motorBike"
  "foamTestTutorial -parallel -full incompressible/pisoFoam/LES/motorBike/lesFiles"
  "foamTestTutorial -parallel -full incompressible/pisoFoam/LES/motorBike/motorBike"
  "foamTestTutorial -parallel -full incompressible/pisoFoam/RAS/cavity"
  "foamTestTutorial -parallel -full incompressible/porousSimpleFoam/angledDuct/explicit"
  "foamTestTutorial -parallel -full incompressible/porousSimpleFoam/angledDuct/implicit"
  "foamTestTutorial -parallel -full incompressible/porousSimpleFoam/straightDuctImplicit"
  "foamTestTutorial -parallel -full incompressible/shallowWaterFoam/squareBump"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/airFoil2D"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/backwardFacingStep2D"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/bump2D"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/bump2D/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/mixerVessel2D"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/motorBike"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/pipeCyclic"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/pitzDaily_fused"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/rotatingCylinders"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/rotorDisk"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/simpleCar"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/squareBend"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/T3A"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/turbineSiting"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/turbulentFlatPlate"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/turbulentFlatPlate/setups.orig/common"
  "foamTestTutorial -parallel -full incompressible/simpleFoam/windAroundBuildings"
  "foamTestTutorial -parallel -full incompressible/SRFPimpleFoam/rotor2D"
  "foamTestTutorial -parallel -full IO/cavity_parProfiling"
  "foamTestTutorial -parallel -full IO/dictionary"
  "foamTestTutorial -parallel -full IO/fileHandler"
  "foamTestTutorial -parallel -full IO/fileHandler_dynamicCode"
  "foamTestTutorial -parallel -full IO/systemCall"
  "foamTestTutorial -parallel -full lagrangian/coalChemistryFoam/simplifiedSiwek"
  "foamTestTutorial -parallel -full lagrangian/icoUncoupledKinematicParcelDyMFoam/mixerVesselAMI2D"
  "foamTestTutorial -parallel -full lagrangian/icoUncoupledKinematicParcelFoam/hopper"
  "foamTestTutorial -parallel -full lagrangian/kinematicParcelFoam/drippingChair"
  "foamTestTutorial -parallel -full lagrangian/kinematicParcelFoam/particleDrag"
  "foamTestTutorial -parallel -full lagrangian/kinematicParcelFoam/particleDrag/parcelInBox"
  "foamTestTutorial -parallel -full lagrangian/kinematicParcelFoam/pitzDailyWithSprinklers"
  "foamTestTutorial -parallel -full lagrangian/kinematicParcelFoam/windshield"
  "foamTestTutorial -parallel -full lagrangian/MPPICFoam/cyclone"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/airRecirculationRoom"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/airRecirculationRoom/transient"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/cylinder"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/filter"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/hotBoxes"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/liquidFilmStepWithSprinklers"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/parcelInBox"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/rectangularChannel"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/recycleParticles"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/rivuletPanel"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/splashPanel"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/splashPanelFilm"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/verticalChannel"
  "foamTestTutorial -parallel -full lagrangian/reactingParcelFoam/verticalChannelLTS"
  "foamTestTutorial -parallel -full lagrangian/simpleReactingParcelFoam/verticalChannel"
  "foamTestTutorial -parallel -full lagrangian/sprayFoam/aachenBomb"
  "foamTestTutorial -parallel -full lagrangian/uncoupledKinematicParcelDyMFoam/rotor2DAMI"
  "foamTestTutorial -parallel -full mesh/blockMesh/mergePairs"
  "foamTestTutorial -parallel -full mesh/blockMesh/pipe"
  "foamTestTutorial -parallel -full mesh/blockMesh/sphere7"
  "foamTestTutorial -parallel -full mesh/blockMesh/sphere7ProjectedEdges"
  "foamTestTutorial -parallel -full mesh/blockMesh/sphere"
  "foamTestTutorial -parallel -full mesh/blockMesh/spheroid7Projected"
  "foamTestTutorial -parallel -full mesh/blockMesh/spheroidProjected"
  "foamTestTutorial -parallel -full mesh/createPatch/multiRegionHeater_autoPatch"
  "foamTestTutorial -parallel -full mesh/createPatch/TJunctionSwitching_createPatch"
  "foamTestTutorial -parallel -full mesh/extrudeMesh/faceZoneExtrusion"
  "foamTestTutorial -parallel -full mesh/extrudeMesh/polyline"
  "foamTestTutorial -parallel -full mesh/foamyHexMesh"
  "foamTestTutorial -parallel -full mesh/foamyHexMesh/blob"
  "foamTestTutorial -parallel -full mesh/foamyHexMesh/flange"
  "foamTestTutorial -parallel -full mesh/foamyHexMesh/mixerVessel"
  "foamTestTutorial -parallel -full mesh/foamyHexMesh/simpleShapes"
  "foamTestTutorial -parallel -full mesh/foamyQuadMesh/jaggedBoundary"
  "foamTestTutorial -parallel -full mesh/foamyQuadMesh/OpenCFD"
  "foamTestTutorial -parallel -full mesh/foamyQuadMesh/square"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/badMove"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/bendJunction"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/faceZoneBlock"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/relativeMotion"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/rotorDisk_inclined"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/SnakeRiverCanyon"
  "foamTestTutorial -parallel -full mesh/moveDynamicMesh/twistingColumn"
  "foamTestTutorial -parallel -full mesh/parallel/cavity"
  "foamTestTutorial -parallel -full mesh/parallel/filter"
  "foamTestTutorial -parallel -full mesh/PDRblockMesh/box0"
  "foamTestTutorial -parallel -full mesh/polyDualMesh/missingCorner"
  "foamTestTutorial -parallel -full mesh/refineMesh/cylinder"
  "foamTestTutorial -parallel -full mesh/refineMesh/refineFieldDirs"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/addLayersToFaceZone"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/aerofoilNACA0012_directionalRefinement"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/airfoilWithLayers"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/block_with_curvature"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/distributedTriSurfaceMesh"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/faceZoneRegions"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/flange"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/gap_detection"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/iglooWithFridgesDirectionalRefinement"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/insidePoints"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/motorBike_leakDetection"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/opposite_walls"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/rotated_block"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/sphere_gapClosure"
  "foamTestTutorial -parallel -full mesh/snappyHexMesh/sphere_multiRegion"
  "foamTestTutorial -parallel -full mesh/stitchMesh/simple-cube1"
  "foamTestTutorial -parallel -full multiphase/cavitatingFoam/LES"
  "foamTestTutorial -parallel -full multiphase/cavitatingFoam/LES/throttle3D"
  "foamTestTutorial -parallel -full multiphase/cavitatingFoam/LES/throttle"
  "foamTestTutorial -parallel -full multiphase/cavitatingFoam/RAS/throttle"
  "foamTestTutorial -parallel -full multiphase/compressibleInterDyMFoam/laminar/sloshingTank2D"
  "foamTestTutorial -parallel -full multiphase/compressibleInterDyMFoam/laminar/sphereDrop"
  "foamTestTutorial -parallel -full multiphase/compressibleInterFoam/laminar/climbingRod"
  "foamTestTutorial -parallel -full multiphase/compressibleInterFoam/laminar/depthCharge2D"
  "foamTestTutorial -parallel -full multiphase/compressibleInterFoam/laminar/depthCharge3D"
  "foamTestTutorial -parallel -full multiphase/compressibleInterFoam/laminar/waterCooler"
  "foamTestTutorial -parallel -full multiphase/compressibleInterIsoFoam/laminar/climbingRod"
  "foamTestTutorial -parallel -full multiphase/compressibleInterIsoFoam/laminar/depthCharge2D"
  "foamTestTutorial -parallel -full multiphase/compressibleInterIsoFoam/laminar/depthCharge3D"
  "foamTestTutorial -parallel -full multiphase/compressibleMultiphaseInterFoam/laminar/damBreak4phase"
  "foamTestTutorial -parallel -full multiphase/driftFluxFoam/RAS/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/driftFluxFoam/RAS/tank3D"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/evaporationMultiComponent"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/inertMultiphaseMultiComponent"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/mixerVesselAMI2D"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/oxideFormation"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/poolEvaporation"
  "foamTestTutorial -parallel -full multiphase/icoReactingMultiphaseInterFoam/poolEvaporationMultiComponent"
  "foamTestTutorial -parallel -full multiphase/interCondensatingEvaporatingFoam/condensatingVessel"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/capillaryRise"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/damBreak"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/damBreak/damBreak"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/damBreakPermeable"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/damBreakWithObstacle"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/oscillatingBox"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingCylinder"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingTank2D3DoF"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingTank2D"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingTank3D3DoF"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingTank3D6DoF"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/sloshingTank3D"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/testTubeMixer"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/vofToLagrangian"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/vofToLagrangian/eulerianInjection"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/vofToLagrangian/lagrangianDistributionInjection"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/vofToLagrangian/lagrangianParticleInjection"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/cnoidal"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/irregularMultiDirection"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/mangroveInteraction"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/solitary"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/solitaryGrimshaw"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/solitaryMcCowan"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/stokesI"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/stokesII"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/stokesV"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/streamFunction"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/waveMakerFlap"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/waveMakerMultiPaddleFlap"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/waveMakerMultiPaddlePiston"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/waveMakerPiston"
  "foamTestTutorial -parallel -full multiphase/interFoam/laminar/waves/waveMakerSolitary"
  "foamTestTutorial -parallel -full multiphase/interFoam/LES/nozzleFlow2D"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/angledDuct"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/damBreak"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/damBreak/damBreak"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/damBreakLeakage"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/damBreakPorousBaffle"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/DTCHull"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/DTCHullMoving"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/electrostaticDeposition"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/floatingObject"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/mixerVesselAMI"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/motorBike"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/waterChannel"
  "foamTestTutorial -parallel -full multiphase/interFoam/RAS/weirOverflow"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/damBreak"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/damBreakWithObstacle"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/discInConstantFlow"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/discInConstantFlowCyclicBCs"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/discInConstantPorousFlow"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/discInReversedVortexFlow"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/iobasin"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/notchedDiscInSolidBodyRotation"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/sloshingTank2D"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/sphereInReversedVortexFlow"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/standingWave"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/waveExampleStreamFunction"
  "foamTestTutorial -parallel -full multiphase/interIsoFoam/weirOverflow"
  "foamTestTutorial -parallel -full multiphase/interMixingFoam/laminar/damBreak"
  "foamTestTutorial -parallel -full multiphase/interPhaseChangeDyMFoam/propeller"
  "foamTestTutorial -parallel -full multiphase/interPhaseChangeFoam/cavitatingBullet"
  "foamTestTutorial -parallel -full multiphase/MPPICInterFoam/twoPhasePachuka"
  "foamTestTutorial -parallel -full multiphase/multiphaseEulerFoam/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/multiphaseEulerFoam/damBreak4phase"
  "foamTestTutorial -parallel -full multiphase/multiphaseEulerFoam/damBreak4phaseFine"
  "foamTestTutorial -parallel -full multiphase/multiphaseEulerFoam/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/multiphaseInterFoam/laminar/damBreak4phase"
  "foamTestTutorial -parallel -full multiphase/multiphaseInterFoam/laminar/damBreak4phaseFine"
  "foamTestTutorial -parallel -full multiphase/multiphaseInterFoam/laminar/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/overCompressibleInterDyMFoam/compressibleTwoSimpleRotors"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/floatingBody"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/floatingBody/background"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/floatingBodyWithSpring"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/rigidBodyHull"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/rigidBodyHull/background"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/rigidBodyHull/overset-1"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/rigidBodyHull/overset-2"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/simpleRotor"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/twoSimpleRotors"
  "foamTestTutorial -parallel -full multiphase/overInterDyMFoam/twoSquaresOutDomain"
  "foamTestTutorial -parallel -full multiphase/overInterPhaseChangeDyMFoam/twoSimpleRotors"
  "foamTestTutorial -parallel -full multiphase/potentialFreeSurfaceDyMFoam/oscillatingBox"
  "foamTestTutorial -parallel -full multiphase/potentialFreeSurfaceFoam/oscillatingBox"
  "foamTestTutorial -parallel -full multiphase/reactingMultiphaseEulerFoam/laminar/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/reactingMultiphaseEulerFoam/laminar/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/reactingMultiphaseEulerFoam/RAS/wallBoiling1D_2phase"
  "foamTestTutorial -parallel -full multiphase/reactingMultiphaseEulerFoam/RAS/wallBoiling1D_3phase"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/bubbleColumnEvaporating"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/bubbleColumnEvaporatingDissolving"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/bubbleColumnIATE"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/fluidisedBed"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/injection"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/laminar/steamInjection"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/LES/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/bubbleColumnEvaporatingReacting"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/bubbleColumnPolydisperse"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/fluidisedBed"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/wallBoiling1D"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/wallBoiling"
  "foamTestTutorial -parallel -full multiphase/reactingTwoPhaseEulerFoam/RAS/wallBoilingIATE"
  "foamTestTutorial -parallel -full multiphase/twoLiquidMixingFoam/lockExchange"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/laminar/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/laminar/bubbleColumnIATE"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/laminar/fluidisedBed"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/laminar/injection"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/laminar/mixerVessel2D"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/LES/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/RAS/bubbleColumn"
  "foamTestTutorial -parallel -full multiphase/twoPhaseEulerFoam/RAS/fluidisedBed"
  "foamTestTutorial -parallel -full preProcessing/createZeroDirectory/cavity"
  "foamTestTutorial -parallel -full preProcessing/createZeroDirectory/motorBike"
  "foamTestTutorial -parallel -full preProcessing/createZeroDirectory/snappyMultiRegionHeater"
  "foamTestTutorial -parallel -full preProcessing/decompositionConstraints/geometric"
  "foamTestTutorial -parallel -full preProcessing/PDRsetFields/simplePipeCage"
  "foamTestTutorial -parallel -full stressAnalysis/solidDisplacementFoam/plateHole"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmDownstreamDevelopment"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmDownstreamDevelopment/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmFlatTerrain"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmFlatTerrain/precursor"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmFlatTerrain/precursor/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmFlatTerrain/successor"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmFlatTerrain/successor/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmForestStability"
  "foamTestTutorial -parallel -full verificationAndValidation/atmosphericModels/atmForestStability/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/multiphase/interIsoFoam/porousDamBreak"
  "foamTestTutorial -parallel -full verificationAndValidation/multiphase/StefanProblem"
  "foamTestTutorial -parallel -full verificationAndValidation/multiphase/StefanProblem/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/divergenceExample"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/nonOrthogonalChannel"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/nonOrthogonalChannel/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/skewnessCavity"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/skewnessCavity/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/schemes/weightedFluxExample"
  "foamTestTutorial -parallel -full verificationAndValidation/turbulenceModels/planeChannel"
  "foamTestTutorial -parallel -full verificationAndValidation/turbulenceModels/planeChannel/setups.orig/common"
  "foamTestTutorial -parallel -full verificationAndValidation/turbulenceModels/planeChannel/setups.orig/EBRSM.setTurbulenceFields"
  "foamTestTutorial -parallel -full verificationAndValidation/turbulentInflow/oneCellThickPlaneChannel"
  "foamTestTutorial -parallel -full verificationAndValidation/turbulentInflow/oneCellThickPlaneChannel/setups.orig/common"
)
########################################
# Result storage
########################################
# Indexed as:
# results["allocator|command|metric"]
#
# metric ∈
# total_mean total_min total_max
# user_mean  user_min  user_max
# system_mean system_min system_max

declare -A results

########################################
# Run experiments
########################################

for allocator in "${!ALLOCATORS[@]}"; do
  allocator_lib="${ALLOCATORS[$allocator]}"

  for cmd in "${COMMANDS[@]}"; do
    echo "Running allocator=${allocator}"
    echo "  command=${cmd}"

    if [[ -n "$allocator_lib" ]]; then
      output=$(
        python "$PYTHON_SCRIPT" \
          -c "$cmd" \
          time \
          --iters 1 \
          --ldpreload "$ALLOC_LIB_DIR" \
          --allocator-replacement "$allocator_lib"
      )
    else
      # GNU malloc (no replacement)
      output=$(
        python "$PYTHON_SCRIPT" \
          -c "$cmd" \
          time \
          --iters 1
      )
    fi

    ####################################
    # Parse output
    ####################################
    # Expect exactly 3 lines:
    # total:  mean min max
    # user:   mean min max
    # system: mean min max

    readarray -t lines <<< "$output"

    if [[ "${#lines[@]}" -ne 3 ]]; then
      echo "ERROR: Expected 3 lines of output, got ${#lines[@]}"
      echo "Output was:"
      echo "$output"
      exit 1
    fi

    read total_mean total_min total_max <<< "${lines[0]}"
    read user_mean  user_min  user_max  <<< "${lines[1]}"
    read sys_mean   sys_min   sys_max   <<< "${lines[2]}"

    key_prefix="${allocator}|${cmd}"

    results["$key_prefix|total_mean"]="$total_mean"
    results["$key_prefix|total_min"]="$total_min"
    results["$key_prefix|total_max"]="$total_max"

    results["$key_prefix|user_mean"]="$user_mean"
    results["$key_prefix|user_min"]="$user_min"
    results["$key_prefix|user_max"]="$user_max"

    results["$key_prefix|system_mean"]="$sys_mean"
    results["$key_prefix|system_min"]="$sys_min"
    results["$key_prefix|system_max"]="$sys_max"
  done
done

########################################
# Dump results (CSV)
########################################

echo
echo "allocator,command,"\
"total_mean,total_min,total_max,"\
"user_mean,user_min,user_max,"\
"system_mean,system_min,system_max"

for allocator in "${!ALLOCATORS[@]}"; do
  for cmd in "${COMMANDS[@]}"; do
    key_prefix="${allocator}|${cmd}"

    echo "${allocator},\"${cmd}\","\
"${results[$key_prefix|total_mean]},"\
"${results[$key_prefix|total_min]},"\
"${results[$key_prefix|total_max]},"\
"${results[$key_prefix|user_mean]},"\
"${results[$key_prefix|user_min]},"\
"${results[$key_prefix|user_max]},"\
"${results[$key_prefix|system_mean]},"\
"${results[$key_prefix|system_min]},"\
"${results[$key_prefix|system_max]}"
  done
done

